### ISSUE TITLE
Team Name is Too Long

### ISSUE THREAD

**Issue by coco0325** [GPAddons/GPBlockHighlightBoundaries#12]
Server version: Paper 1.17.1
Error log: https://pastebin.com/ZsAr5sSa

**Comment by Jikoo** [comment]
Looks like you're using Purpur, not Paper. Had no troubles with Paper when testing this initially on 1.18, but that's an easy fix.

**Comment by Jikoo** [comment]
Okay, after checking around a little more that's a pure 1.17 Spigot issue. Scoreboard display names were allowed to be the correct length of 128 characters but internal names were capped to 16 characters. As of 1.18 it's now capped to 32767 as expected.

I think the "fix" here is going to be to just slap a try/catch around it and call it a day, truncating and setting display name as necessary.
